-- =============================================================================
-- ThinkSync — Sprint 3 Finalization (Phase 2.5): Database Schema Verification & Migration
-- =============================================================================
-- Date:        2026-07-13
-- Scope:       Bring production schema into complete alignment with the backend.
-- Policy:      ADDITIVE ONLY. No table/column/constraint removal, no rename,
--              no data loss, no breaking change. Every statement uses
--              "IF NOT EXISTS" / "IF EXISTS" guards so the file is idempotent
--              and safe to re-run.
--
-- Generated by: automated backend<->schema diff (DATABASE_SCHEMA_AUDIT.md)
--
-- WHAT THIS MIGRATION FIXES
--   1. Adds 3 tables referenced by the backend but defined in NO SQL at all:
--        conversation_audit, idempotency_store, resume_outcomes
--   2. Brings the canonical db/schema.sql into sync by adding the 6 tables that
--      exist only in migrations (agent_runs, approval_requests, approval_audit,
--      project_specifications, worker_heartbeats, workspace_deployments).
--      (They are re-declared here idempotently so this single file is sufficient
--       to bring a fresh database to full parity with the backend.)
--   3. Adds 4 columns the backend reads/writes on `jobs` but no migration creates:
--        conversation_id, conversation_session, cursor_version, spec
--   4. Adds 2 columns the backend requires on `approval_requests`:
--        request_version, resume_token
--   5. Extends the jobs.status CHECK constraint to permit the Sprint 3 interactive
--      wait / resume states, WITHOUT dropping data (old rows keep their values;
--      the constraint only restricts FUTURE writes, and all new values already
--      appear in the enum list).
--   6. Enables RLS + owner-scoped policies on every backend table that lacks them
--      (conversation_audit, idempotency_store, resume_outcomes, agent_runs,
--       approval_requests, approval_audit, project_specifications).
--   7. Adds indexes to support the high-frequency lookups the backend performs.
--
-- OUT OF SCOPE (documented as risks, NOT auto-applied — see DATABASE_SCHEMA_AUDIT.md):
--   * `infra/supabase/schema.sql` is a stale v2 copy; it is NOT the source of truth.
--     Regenerate it from db/schema.sql + migrations instead of editing by hand.
--   * `servers` / `infra` supabase copy uses ssh_auth_method IN ('password','key')
--     while the backend uses IN ('private_key','password') — drift in the DEPLOY
--     artifact only; not touched here to avoid conflict with live deployments.
-- =============================================================================

create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

-- =============================================================================
-- 1. project_specifications  (exists in SPRINT_02A_MIGRATION.sql; restored here for parity)
-- =============================================================================
create table if not exists public.project_specifications (
    id                uuid        primary key default gen_random_uuid(),
    conversation_id   text        not null unique,
    user_id           text        not null default '',
    spec_json         jsonb       not null,
    spec_versions     jsonb       not null default '[]'::jsonb,
    latest_spec_version integer   not null default 0,
    approval_context  jsonb       not null default '{}'::jsonb,
    requirement_events jsonb      not null default '[]'::jsonb,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);

create index if not exists idx_project_specs_conversation
    on public.project_specifications (conversation_id);

-- =============================================================================
-- 2. workspace_deployments  (exists in 20260322_subdomain_deployment.sql; restored for parity)
-- =============================================================================
create table if not exists public.workspace_deployments (
    id           uuid        primary key default gen_random_uuid(),
    workspace_id uuid        not null references public.workspaces(id) on delete cascade,
    port         integer     not null check (port between 1024 and 65535),
    is_active    boolean     not null default false,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now()
);

create index if not exists idx_workspace_deployments_workspace_id
    on public.workspace_deployments (workspace_id);
create index if not exists idx_workspace_deployments_is_active
    on public.workspace_deployments (is_active);

-- =============================================================================
-- 3. agent_runs  (exists in 20260404_agent_runs.sql; restored for parity)
-- =============================================================================
create table if not exists public.agent_runs (
    id           uuid        primary key default gen_random_uuid(),
    user_id      uuid        not null,
    user_email   text        not null,
    server_id    uuid        not null,
    objective    text        not null,
    dry_run      boolean     not null default false,
    allow_write  boolean     not null default false,
    max_steps    integer     not null,
    plan         jsonb       not null,
    results      jsonb       not null,
    summary      text        not null,
    success      boolean     not null default false,
    created_at   timestamptz not null default now()
);

create index if not exists idx_agent_runs_user_id
    on public.agent_runs (user_id);
create index if not exists idx_agent_runs_server_id
    on public.agent_runs (server_id);
create index if not exists idx_agent_runs_created_at
    on public.agent_runs (created_at desc);

-- =============================================================================
-- 4. approval_requests  (exists in SPRINT_03_MIGRATION.sql; restored for parity)
--    + adds request_version & resume_token columns the backend requires.
-- =============================================================================
create table if not exists public.approval_requests (
    approval_id          text        primary key,
    -- CONTRACT FIX (2026-07-13, Phase 2.6): job_id must be uuid to match jobs.id (uuid).
    -- Backend proves it: agent_service.py writes `job_id = str(uuid4())` (a full UUID).
    -- A `text` column cannot form an FK to jobs.id (uuid) — PostgreSQL rejects it with
    -- "foreign key constraint cannot be implemented ... incompatible types: text and uuid".
    -- approval_id STAYS text because the backend generates it as uuid4().hex[:16] (NOT a uuid).
    job_id               uuid        not null references public.jobs(id) on delete cascade,
    conversation_id      text        not null,
    approval_type        text        not null,
    status               text        not null default 'pending',
    title                text        default '',
    description          text        default '',
    risk_level           text        default 'medium',
    affected_files       jsonb       default '[]',
    affected_commands    jsonb       default '[]',
    affected_assumptions jsonb       default '[]',
    context              jsonb       default '{}',
    created_at           timestamptz default now(),
    resolved_at          timestamptz,
    resolved_by          text        default '',
    decision             text,
    reason               text        default '',
    spec_version         integer,
    requirement_version  integer,
    -- ---- Sprint 3B / 3C additions (additive) ----
    request_version      integer     not null default 0,
    resume_token         jsonb
);

create index if not exists idx_approval_requests_job
    on public.approval_requests (job_id);
create index if not exists idx_approval_requests_status
    on public.approval_requests (status);

-- =============================================================================
-- 5. approval_audit  (exists in SPRINT_03_MIGRATION.sql; restored for parity)
-- =============================================================================
create table if not exists public.approval_audit (
    event_id       text        primary key,
    approval_id    text        not null references public.approval_requests(approval_id) on delete cascade,
    -- CONTRACT FIX (2026-07-13, Phase 2.6): job_id uuid to match jobs.id (uuid). See approval_requests note.
    job_id         uuid        not null references public.jobs(id) on delete cascade,
    conversation_id text       not null,
    event_type     text        not null,
    timestamp      timestamptz default now(),
    decision       text,
    reason         text        default '',
    "user"         text        default '',
    metadata       jsonb       default '{}'
);

create index if not exists idx_approval_audit_approval
    on public.approval_audit (approval_id);
create index if not exists idx_approval_audit_job
    on public.approval_audit (job_id);

-- =============================================================================
-- 6. worker_heartbeats  (exists in 20260601_reliability_sprint_v2.sql; restored for parity)
-- =============================================================================
create table if not exists public.worker_heartbeats (
    id             uuid        primary key default gen_random_uuid(),
    worker_id      text        not null,
    job_id         uuid        references public.jobs(id) on delete set null,
    last_heartbeat timestamptz not null default now(),
    started_at     timestamptz not null default now(),
    status         text        not null default 'active'
        check (status in ('active', 'idle', 'stale', 'shutdown')),
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now(),
    unique (worker_id)
);

create index if not exists idx_worker_heartbeats_job
    on public.worker_heartbeats (job_id);

-- =============================================================================
-- 7. conversation_audit  *** MISSING FROM ALL SQL — CREATED HERE ***
--    Persisted via AuditEvent.model_dump_json() (see services/conversation_audit.py).
--    Columns mirror the AuditEvent model: event_id, job_id, conversation_id,
--    session_id, event_type, actor, content (jsonb), spec_version, cursor_version,
--    timestamp.
-- =============================================================================
create table if not exists public.conversation_audit (
    event_id         text        primary key,
    job_id           text        not null,
    conversation_id  text        not null default '',
    session_id       text        not null default '',
    event_type       text        not null,
    actor            text        not null default 'user',
    content          jsonb       not null default '{}'::jsonb,
    spec_version     integer,
    cursor_version   integer,
    timestamp        timestamptz not null default now()
);

create index if not exists idx_conversation_audit_job
    on public.conversation_audit (job_id);
create index if not exists idx_conversation_audit_conversation
    on public.conversation_audit (conversation_id);
create index if not exists idx_conversation_audit_job_event
    on public.conversation_audit (job_id, event_type);

-- =============================================================================
-- 8. idempotency_store  *** MISSING FROM ALL SQL — CREATED HERE ***
--    Written by IdempotencyStore.record() (services/conversation_reliability.py).
-- =============================================================================
create table if not exists public.idempotency_store (
    id            uuid        primary key default gen_random_uuid(),
    operation_id  text        not null,
    job_id        text        not null,
    result        jsonb       not null default '{}'::jsonb,
    created_at    timestamptz not null default now(),
    unique (operation_id, job_id)
);

create index if not exists idx_idempotency_store_op_job
    on public.idempotency_store (operation_id, job_id);
create index if not exists idx_idempotency_store_job
    on public.idempotency_store (job_id);

-- =============================================================================
-- 9. resume_outcomes  *** MISSING FROM ALL SQL — CREATED HERE ***
--    Written by ExactlyOnceResumeGuard.record_resume() (services/conversation_reliability.py).
-- =============================================================================
create table if not exists public.resume_outcomes (
    id            uuid        primary key default gen_random_uuid(),
    approval_id   text        not null,
    -- CONTRACT FIX (2026-07-13, Phase 2.6): job_id uuid to match jobs.id (uuid). See approval_requests note.
    job_id        uuid        not null references public.jobs(id) on delete cascade,
    resume_result jsonb       not null default '{}'::jsonb,
    created_at    timestamptz not null default now()
);

create index if not exists idx_resume_outcomes_approval
    on public.resume_outcomes (approval_id);
create index if not exists idx_resume_outcomes_job
    on public.resume_outcomes (job_id);

-- =============================================================================
-- 10. Extend `jobs` with the 4 columns the backend reads/writes but no migration creates
--     (resume_manager.py, conversation_continuation.py, ConversationSessionStore).
-- =============================================================================
alter table public.jobs
    add column if not exists conversation_id       text,
    add column if not exists conversation_session  jsonb,
    add column if not exists cursor_version        integer     not null default 0,
    add column if not exists spec                  jsonb;

create index if not exists idx_jobs_conversation_id
    on public.jobs (conversation_id);

-- =============================================================================
-- 11. Extend jobs.status CHECK constraint to cover Sprint 3 interactive states.
--     Additive + backward-safe: existing rows keep their current status; the new
--     enum list is a SUPERSET of the old one, so no existing value is rejected.
-- =============================================================================
do $$
begin
    if exists (
        select 1 from pg_constraint
        where conname = 'jobs_status_check'
          and conrelid = 'public.jobs'::regclass
    ) then
        alter table public.jobs drop constraint jobs_status_check;
    end if;
end $$;

alter table public.jobs
    add constraint jobs_status_check
    check (
        status in (
            'queued',
            'claimed',
            'running',
            'waiting_for_llm',
            'waiting_for_user',
            'approved',
            'rejected',
            'resumed',
            'paused',
            'cancelled',
            'completed',
            'failed',
            'abandoned',
            'recoverable'
        )
    );

-- =============================================================================
-- 12. Row-Level Security — enable + owner-scoped policies on every backend table.
--     Pre-existing tables already have RLS in db/schema.sql; the clauses below
--     are idempotent (DROP POLICY IF EXISTS + CREATE POLICY).
-- =============================================================================

-- 12a. conversation_audit (job-scoped owner isolation)
alter table public.conversation_audit enable row level security;
drop policy if exists "Users manage own conversation audit" on public.conversation_audit;
create policy "Users manage own conversation audit"
    on public.conversation_audit
    for all
    using (
        exists (
            select 1 from public.jobs j
            where j.id::text = conversation_audit.job_id
              and j.user_id = auth.uid()
        )
    )
    with check (
        exists (
            select 1 from public.jobs j
            where j.id::text = conversation_audit.job_id
              and j.user_id = auth.uid()
        )
    );

-- 12b. idempotency_store (job-scoped owner isolation)
alter table public.idempotency_store enable row level security;
drop policy if exists "Users manage own idempotency store" on public.idempotency_store;
create policy "Users manage own idempotency store"
    on public.idempotency_store
    for all
    using (
        exists (
            select 1 from public.jobs j
            where j.id::text = idempotency_store.job_id
              and j.user_id = auth.uid()
        )
    )
    with check (
        exists (
            select 1 from public.jobs j
            where j.id::text = idempotency_store.job_id
              and j.user_id = auth.uid()
        )
    );

-- 12c. resume_outcomes (job-scoped owner isolation)
alter table public.resume_outcomes enable row level security;
drop policy if exists "Users manage own resume outcomes" on public.resume_outcomes;
create policy "Users manage own resume outcomes"
    on public.resume_outcomes
    for all
    using (
        exists (
            select 1 from public.jobs j
            where j.id = resume_outcomes.job_id
              and j.user_id = auth.uid()
        )
    )
    with check (
        exists (
            select 1 from public.jobs j
            where j.id = resume_outcomes.job_id
              and j.user_id = auth.uid()
        )
    );

-- 12d. agent_runs (direct user_id ownership)
alter table public.agent_runs enable row level security;
drop policy if exists "Users manage own agent runs" on public.agent_runs;
create policy "Users manage own agent runs"
    on public.agent_runs
    for all
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- 12e. approval_requests (job-scoped owner isolation)
alter table public.approval_requests enable row level security;
drop policy if exists "Users manage own approval requests" on public.approval_requests;
create policy "Users manage own approval requests"
    on public.approval_requests
    for all
    using (
        exists (
            select 1 from public.jobs j
            where j.id = approval_requests.job_id
              and j.user_id = auth.uid()
        )
    )
    with check (
        exists (
            select 1 from public.jobs j
            where j.id = approval_requests.job_id
              and j.user_id = auth.uid()
        )
    );

-- 12f. approval_audit (job-scoped owner isolation)
alter table public.approval_audit enable row level security;
drop policy if exists "Users manage own approval audit" on public.approval_audit;
create policy "Users manage own approval audit"
    on public.approval_audit
    for all
    using (
        exists (
            select 1 from public.jobs j
            where j.id = approval_audit.job_id
              and j.user_id = auth.uid()
        )
    )
    with check (
        exists (
            select 1 from public.jobs j
            where j.id = approval_audit.job_id
              and j.user_id = auth.uid()
        )
    );

-- 12g. project_specifications (conversation-scoped; owner derived via job linkage)
-- Note: project_specifications stores conversation_id only (no direct user_id).
-- Owner isolation is enforced through the owning job when one exists; where no job
-- linkage is available the policy falls back to the stored user_id column.
alter table public.project_specifications enable row level security;
drop policy if exists "Users manage own project specifications" on public.project_specifications;
create policy "Users manage own project specifications"
    on public.project_specifications
    for all
    using (
        user_id = auth.uid()::text
        or exists (
            select 1 from public.jobs j
            where j.conversation_id = project_specifications.conversation_id
              and j.user_id = auth.uid()
        )
    )
    with check (
        user_id = auth.uid()::text
        or exists (
            select 1 from public.jobs j
            where j.conversation_id = project_specifications.conversation_id
              and j.user_id = auth.uid()
        )
    );

-- =============================================================================
-- 13. Final verification helpers (comment-only; run manually if desired)
-- =============================================================================
-- select table_name from information_schema.tables
-- where table_schema = 'public'
-- order by table_name;
--
-- select column_name, data_type from information_schema.columns
-- where table_name = 'jobs' order by ordinal_position;
