from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field
from pydantic.alias_generators import to_snake
from pydantic.functional_validators import AfterValidator
from typing_extensions import Annotated


def _non_empty_str(value: str) -> str:
    cleaned = (value or "").strip()
    if not cleaned:
        raise ValueError("Value must be a non-empty string")
    return cleaned


NonEmptyStr = Annotated[str, AfterValidator(_non_empty_str)]


class AgentTier(str, Enum):
    FORGE_V1 = "forge-v1"
    FORGE_V2 = "forge-v2"


class AgentJobStatus(str, Enum):
    QUEUED = "queued"
    RUNNING = "running"
    WAITING_FOR_LLM = "waiting_for_llm"
    COMPLETED = "completed"
    FAILED = "failed"


class ToolName(str, Enum):
    RUN_COMMAND = "run_command"
    CHECK_DISK = "check_disk"
    CHECK_MEMORY = "check_memory"
    RESTART_SERVICE = "restart_service"
    READ_LOGS = "read_logs"
    DEPLOY_APP = "deploy_app"
    DEPLOY_NEXTJS_APP = "deploy_nextjs_app"
    LIST_FILES = "list_files"
    READ_FILE = "read_file"
    WRITE_FILE = "write_file"
    LIST_PROCESSES = "list_processes"


class DecisionAction(str, Enum):
    CONTINUE = "continue"
    RETRY = "retry"
    MODIFY = "modify"
    ABORT = "abort"


class AgentPlanStep(BaseModel):
    step: int = Field(..., ge=1)
    command: str
    rationale: str
    approved: bool = True


class AgentRunRequest(BaseModel):
    server_id: str
    objective: str = Field(..., min_length=3, max_length=500)
    max_steps: int = Field(default=5, ge=1, le=10)
    allow_write: bool = False
    dry_run: bool = False
    step_timeout_seconds: int | None = Field(default=None, ge=5, le=300)
    max_concurrency: int | None = Field(default=None, ge=1, le=5)


class AgentExecutionResult(BaseModel):
    command: str
    output: str
    exit_code: int
    executed_at: datetime


class ArchitectureHistoryItem(BaseModel):
    id: str
    objective: str
    summary: str
    success: bool
    created_at: datetime


class AgentRunResponse(BaseModel):
    agent: AgentTier = AgentTier.FORGE_V1
    objective: str
    dry_run: bool
    policy: dict[str, str | int | bool]
    plan: list[AgentPlanStep]
    results: list[AgentExecutionResult]
    summary: str


class AgentOrchestrationRequest(BaseModel):
    workspace_id: str
    message: str = Field(..., min_length=3, max_length=20000)
    max_steps: int = Field(default=5, ge=1, le=10)
    allow_write: bool = False
    dry_run: bool = False
    step_timeout_seconds: int | None = Field(default=None, ge=5, le=300)
    max_concurrency: int | None = Field(default=None, ge=1, le=5)


class AgentOrchestrationResponse(BaseModel):
    agent: AgentTier = AgentTier.FORGE_V1
    chat_id: str
    user_message_id: str
    assistant_message_id: str
    run: AgentRunResponse
    architecture_history: list[ArchitectureHistoryItem]


class AgentPlanResponse(BaseModel):
    agent: AgentTier = AgentTier.FORGE_V1
    objective: str
    dry_run: bool = True
    policy: dict[str, str | int | bool]
    plan: list[AgentPlanStep]
    summary: str


class AgentAsyncRunAccepted(BaseModel):
    job_id: str
    status: AgentJobStatus = AgentJobStatus.QUEUED


class AgentJobResponse(BaseModel):
    job_id: str
    status: AgentJobStatus
    run: AgentRunResponse | None = None
    error: str | None = None


# ── Forge v2 models ────────────────────────────────────────────────────────────


class AgentStep(BaseModel):
    """A single step in an LLM-generated execution plan."""

    step: int = Field(..., ge=1)
    tool: str = Field(..., min_length=1)
    args: dict = Field(default_factory=dict)
    reason: str = Field(..., min_length=1)
    risk_level: str = "safe"


class AgentPlan(BaseModel):
    """Full execution plan generated by the LLM."""

    objective: str
    steps: list[AgentStep]
    context_summary: str = ""


class StepResult(BaseModel):
    """Result from executing one agent step via a tool."""

    step: int
    tool: ToolName
    args: dict[str, Any]
    command: str = ""
    command_type: str = "ACTION"
    stdout: str = ""
    stderr: str = ""
    exit_code: int = 0
    duration_ms: int = 0
    executed_at: datetime
    success: bool
    validation_passed: bool = False
    status: str = "pending"
    agent_reasoning: str = ""


class AgentDecision(BaseModel):
    """LLM decision after evaluating a step result."""

    action: DecisionAction
    reason: str
    modified_step: AgentStep | None = None
    summary_so_far: str = ""


class ToolCallingLoopResult(BaseModel):
    """Result of the OpenAI tool-calling agent loop."""

    task_mode: str = "complex"
    plan: list[AgentStep] = []
    steps: list[StepResult] = []
    decisions: list[AgentDecision] = []
    errors: list[dict[str, Any]] = []
    retries: list[dict[str, Any]] = []
    summary: str = ""
    success: bool = True
    steps_taken: int = 0


class ForgeV2RunRequest(BaseModel):
    workspace_id: str | None = None
    server_id: str
    objective: str = Field(..., min_length=3, max_length=1000)
    max_steps: int = Field(default=8, ge=1, le=20)
    max_retries: int | None = Field(default=None, ge=0, le=5)
    allow_write: bool | None = None
    dry_run: bool = False
    step_timeout_seconds: int | None = Field(default=None, ge=5, le=600)


class ForgeV2StepAudit(BaseModel):
    """Row persisted to agent_runs for each step."""

    job_id: str
    step: int
    tool: str
    args: dict[str, Any]
    stdout: str
    stderr: str
    exit_code: int
    duration_ms: int
    decision: str
    decision_reason: str
    executed_at: datetime


class ForgeV2RunResponse(BaseModel):
    agent: AgentTier = AgentTier.FORGE_V2
    job_id: str
    objective: str
    dry_run: bool
    plan: list[AgentStep]
    results: list[StepResult]
    decisions: list[AgentDecision]
    summary: str
    success: bool


class ForgeV2JobResponse(BaseModel):
    job_id: str
    status: AgentJobStatus
    run: ForgeV2RunResponse | None = None
    error: str | None = None


class ForgeV2PlanResponse(BaseModel):
    agent: AgentTier = AgentTier.FORGE_V2
    job_id: str
    objective: str
    plan: list[AgentStep]
    context_summary: str


# ── Requirement Discovery (Sprint 2F) ─────────────────────────────────
#
#  Sprint 2F strengthens the architecture introduced in 2E.
#  Events become the ONLY authoritative source.
#  Snapshots become rebuildable projections.
#  Domain events, resolution policies, and projection verification added.
# ─────────────────────────────────────────────────────────────────────────────

# ---------------------------------------------------------------------------
# Sprint 2G additions — Event Schema Versioning + Checkpoints + Protocols
# ---------------------------------------------------------------------------

class EventSchemaVersion(int, Enum):
    """Schema version for RequirementEvent payload (Objective 2).

    v1  — initial (Sprint 2E/2F)
    v2  — added ``notes`` + ``metadata.priority``
    v3  — added ``affects`` + ``supersedes`` validation

    Events are IMMUTABLE.  Older events are UPCAST via ``EventUpcaster``.
    """
    v1 = 1
    v2 = 2
    v3 = 3


# ---------------------------------------------------------------------------
# Objective 3 — EventUpcaster
# ---------------------------------------------------------------------------

class EventUpcaster:
    """Upcast older event schemas to the current internal model (Objective 3).

    Events are immutable — their stored JSON never changes.
    When the schema evolves, ``upcast()`` converts old payloads
    into the CURRENT in-memory representation before projection.

    Dispatch architecture:
      - ``_upcast_v1_to_v1()``   — identity (baseline)
      - ``_upcast_v2_to_v1()``   — (future) v2 → v1
      - ``_upcast_v3_to_v1()``   — (future) v3 → v1
      - Add new methods when schema evolves; never modify old ones.

    This means OLD events continue to work forever.
    """
    CURRENT_VERSION = EventSchemaVersion.v1

    @classmethod
    def upcast(cls, events: list[RequirementEvent]) -> list[RequirementEvent]:
        """Upcast all events to CURRENT_VERSION.

        Returns a NEW list — original events are NOT mutated.

        Fail-fast rules:
          - version == CURRENT_VERSION → return unchanged (identity)
          - version < CURRENT_VERSION  → look up upcaster method;
            if NOT found: raise RuntimeError (unsupported old schema)
          - version > CURRENT_VERSION  → raise RuntimeError
            (future schema version — code must be upgraded first)
          - NO code path silently returns the event unchanged
        """
        result: list[RequirementEvent] = []
        for ev in events:
            target = cls.CURRENT_VERSION
            source = ev.event_schema_version

            if source == target:
                # v1 → v1: identity; event is already current
                result.append(ev)

            elif source > target:
                # Future schema version — code is outdated
                raise RuntimeError(
                    f"[EventUpcaster] event {ev.event_id}: "
                    f"event_schema_version={source.name} is newer than "
                    f"current={target.name}. "
                    f"Upgrade ThinkSync to handle this schema version."
                )

            else:
                # source < target: look up the upcaster method
                method_name = f"_upcast_{source.name}_to_{target.name}"
                upcast_method = getattr(cls, method_name, None)
                if upcast_method is not None:
                    result.append(upcast_method(ev))
                else:
                    raise RuntimeError(
                        f"[EventUpcaster] event {ev.event_id}: "
                        f"no upcaster found for {source.name} → {target.name}. "
                        f"Implement `{method_name}` on EventUpcaster."
                    )
        return result

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Upcast methods (add new ones when schema evolves)
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @classmethod
    def _upcast_v1_to_v1(cls, event: RequirementEvent) -> RequirementEvent:
        """v1 → v1: identity.  Event is already current."""
        return event


# ---------------------------------------------------------------------------
# Objective 6 — ProjectionContext (replaces RequirementResolutionContext)
# ---------------------------------------------------------------------------

@dataclass
class ProjectionContext:
    """Context bundle passed to the projection engine (Objective 6).

    Replaces ``RequirementResolutionContext`` with a cleaner contract.
    The engine reads ONLY this context — it never accesses repos directly.
    """
    events: list[RequirementEvent] = field(default_factory=list)
    checkpoint: SnapshotCheckpoint | None = None
    policy: ResolutionPolicy = ResolutionPolicy.NEWEST_WINS
    schema_version: EventSchemaVersion = EventSchemaVersion.v1
    metadata: dict[str, Any] = field(default_factory=dict)

    # ── computed by engine ─────────────────────────────────────────────
    resolved_text: str = ""
    intent: IntentType = IntentType.CREATE
    replay_duration_ms: int = 0
    projection_version: int = 1


# ---------------------------------------------------------------------------
# Objective 5 — SnapshotCheckpoint
# ---------------------------------------------------------------------------

class SnapshotCheckpoint(BaseModel):
    """Checkpoint for incremental replay (Objective 5).

    Instead of replaying ALL events every time, the engine:
      1. Loads the latest checkpoint (full snapshot at event_index)
      2. Replays ONLY events AFTER event_index
      3. Saves a new checkpoint periodically

    This makes replay O(delta) instead of O(total_events).
    """
    checkpoint_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    snapshot_version: int = 1
    event_index: int = 0        # how many events were replayed to produce this
    snapshot_hash: str = ""   # hash of the snapshot at this checkpoint
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    event_count: int = 0    # total events in store at checkpoint time


# ---------------------------------------------------------------------------
# Objective 10 — ReplayMetrics
# ---------------------------------------------------------------------------

class ReplayMetrics(BaseModel):
    """Metrics collected during projection replay (Objective 10).

    Fields:
      - total_events:       total events in store (for context)
      - loaded_events:      events actually loaded (delta if checkpoint hit, full otherwise)
      - replayed_events:   events the engine actually processed
      - checkpoint_hits:   how many times a checkpoint was found
      - checkpoint_misses: how many times no checkpoint existed
      - checkpoint_used:    True if a checkpoint existed at load time
      - projection_mode:    "full_rebuild" (until checkpoint restore is implemented)
      - upcast_count:     how many events were upcast
      - conflict_count:    how many conflicts were detected
    """
    total_events: int = 0
    loaded_events: int = 0      # events actually loaded from store
    replayed_events: int = 0    # events the engine processed (currently == loaded_events)
    checkpoint_hits: int = 0
    checkpoint_misses: int = 0
    checkpoint_used: bool = False
    projection_mode: str = "full_rebuild"
    projection_time_ms: int = 0
    upcast_count: int = 0      # how many events were upcast
    conflict_count: int = 0


# ---------------------------------------------------------------------------
# Objective 9 — Infrastructure Protocols (explicit contracts)
# ---------------------------------------------------------------------------
# These protocols define the contract each infrastructure service must fulfil.
# Implementations live in ``services/requirement_discovery.py``.
# ---------------------------------------------------------------------------

class EventStoreProtocol(Protocol):
    """Contract for RequirementEventStore (Objective 1, 9)."""
    async def append(self, conversation_id: str, event: RequirementEvent) -> None: ...
    async def load_events(self, conversation_id: str) -> list[RequirementEvent]: ...
    async def load_since(self, conversation_id: str, after: datetime) -> list[RequirementEvent]: ...


class SnapshotRepositoryProtocol(Protocol):
    """Contract for SnapshotRepository (Objective 4, 9)."""
    async def save_snapshot(self, conversation_id: str, snapshot: RequirementSnapshot) -> None: ...
    async def load_latest(self, conversation_id: str) -> RequirementSnapshot | None: ...
    async def load_version(self, conversation_id: str, version: int) -> RequirementSnapshot | None: ...
    async def load_checkpoint(self, conversation_id: str) -> SnapshotCheckpoint | None: ...
    async def save_checkpoint(self, conversation_id: str, checkpoint: SnapshotCheckpoint) -> None: ...
    async def delete_cache(self, conversation_id: str) -> None: ...


class ProjectionContextProtocol(Protocol):
    """Contract for ProjectionContext (Objective 6, 9)."""
    events: list[RequirementEvent]
    checkpoint: SnapshotCheckpoint | None
    policy: ResolutionPolicy
    schema_version: EventSchemaVersion


class ProjectionEngineProtocol(Protocol):
    """Contract for RequirementProjectionEngine (Objective 7, 9)."""
    def project(self, context: ProjectionContext) -> RequirementSnapshot: ...


class ProjectionVerifierProtocol(Protocol):
    """Contract for ProjectionVerifier (Objective 8, 9)."""
    def verify(
        self, events: list[RequirementEvent], snapshot: RequirementSnapshot,
    ) -> tuple[bool, list[str]]: ...


class EventUpcasterProtocol(Protocol):
    """Contract for EventUpcaster (Objective 3, 9)."""
    def upcast(self, event: RequirementEvent) -> RequirementEvent: ...


class CheckpointRepositoryProtocol(Protocol):
    """Contract for checkpoint persistence (Objective 5, 9)."""
    async def save(self, conversation_id: str, checkpoint: SnapshotCheckpoint) -> None: ...
    async def load(self, conversation_id: str) -> SnapshotCheckpoint | None: ...


# ---------------------------------------------------------------------------
# RequirementResolutionContext — DEPRECATED (use ProjectionContext)
# ---------------------------------------------------------------------------
# Kept for backward compatibility with Sprint 2F code paths.
# New code MUST use ``ProjectionContext``.
# ---------------------------------------------------------------------------


# ── (The rest of the Sprint 2F models continue below) ────────────────────

class ResolutionPolicy(str, Enum):
    """Configurable resolution policies (Objective 5).

    Policies control HOW the ``RequirementResolutionEngine`` resolves
    conflicting events into a ``RequirementSnapshot``.

    ``NEWEST_WINS``  — default; newest event wins per field/component.
    ``PRIORITY_WINS`` — highest-priority event wins (future: priority
                         will be set by Approval System).
    ``MANUAL``       — conflicts are NOT resolved; user must decide.
    ``MERGE``        — merge non-conflicting fields; keep conflicts.
    ``REJECT``       — reject any event that creates a conflict.
    """
    NEWEST_WINS  = "newest_wins"
    PRIORITY_WINS = "priority_wins"
    MANUAL       = "manual"
    MERGE        = "merge"
    REJECT       = "reject"


@dataclass
class RequirementResolutionContext:
    """Context bundle passed to the resolution engine (Objective 6).

    The engine reads ONLY this context — it never reaches into global
    state, never imports planner/executor, and never calls external APIs.

    This makes the engine fully deterministic and testable.
    """
    policy: ResolutionPolicy = ResolutionPolicy.NEWEST_WINS
    events: list[RequirementEvent] = field(default_factory=list)
    active_components: list[DynamicComponent] = field(default_factory=list)
    assumptions: list[Assumption] = field(default_factory=list)
    conflicts: list[RequirementConflict] = field(default_factory=list)
    unknowns: dict[str, UnknownType] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)

    # ── computed by engine ───────────────────────────────────────────────
    resolved_text: str = ""
    intent: IntentType = IntentType.CREATE
    replay_duration_ms: int = 0
    projection_version: int = 1


# ---------------------------------------------------------------------------
# Objective 1 — RequirementEventStore
# ---------------------------------------------------------------------------

class RequirementEventStore:
    """The ONLY authoritative source of truth (Objective 1).

    All requirement events are appended here.
    No other layer may mutate events.
    Snapshots are derived (projected) from this store.

    Responsibilities:
      - append(event)           — immutable append; never edit
      - get_events(conversation_id)  — full event log
      - get_events_since(conversation_id, after_timestamp)
      - rebuild_snapshot(conversation_id, policy)  — deterministic replay
      - compact(conversation_id)  — (future) archive old events

    The store is backed by ``project_specifications.requirement_events``
    (JSONB in Postgres) for now.  A dedicated ``requirement_events``
    table can be introduced in Sprint 3 without changing this interface.
    """
    TABLE = "project_specifications"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Append (immutable)
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @classmethod
    async def append(cls, conversation_id: str, event: RequirementEvent) -> None:
        """Append ONE immutable event to the store."""
        from core.database import get_supabase
        now = datetime.now(timezone.utc).isoformat()
        try:
            result = (
                get_supabase()
                .table(cls.TABLE)
                .select("requirement_events")
                .eq("conversation_id", conversation_id)
                .maybe_single()
                .execute()
            )
            events: list[dict] = []
            if result and result.data:
                events = result.data.get("requirement_events") or []
            events.append(event.model_dump(mode="json"))
            get_supabase().table(cls.TABLE).upsert({
                "conversation_id": conversation_id,
                "requirement_events": events,
                "updated_at": now,
            }, on_conflict="conversation_id").execute()
        except Exception as exc:
            logger.error("[event_store] append failed: %s", exc, exc_info=True)
            raise

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Read
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @classmethod
    async def get_events(cls, conversation_id: str) -> list[RequirementEvent]:
        """Return the full event log (oldest → newest)."""
        try:
            from core.database import get_supabase
            result = (
                get_supabase()
                .table(cls.TABLE)
                .select("requirement_events")
                .eq("conversation_id", conversation_id)
                .maybe_single()
                .execute()
            )
            if result and result.data:
                raw = result.data.get("requirement_events") or []
                return [RequirementEvent(**r) for r in raw]
        except Exception as exc:
            logger.warning("[event_store] get_events failed: %s", exc)
        return []

    @classmethod
    async def get_events_since(
        cls, conversation_id: str, after: datetime,
    ) -> list[RequirementEvent]:
        """Return events after a given timestamp (for incremental projection)."""
        all_events = await cls.get_events(conversation_id)
        return [e for e in all_events if e.timestamp > after]

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Deterministic replay (Objective 1 — snapshot = projection)
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @classmethod
    async def rebuild_snapshot(
        cls,
        conversation_id: str,
        policy: ResolutionPolicy | None = None,
    ) -> RequirementSnapshot:
        """Rebuild a ``RequirementSnapshot`` from ALL events in the store.

        This is the authoritative rebuild path.  Same events + same policy
        ALWAYS produce the same snapshot (deterministic).

        The result is also persisted as ``latest_snapshot``.
        """
        policy = policy or ResolutionPolicy.NEWEST_WINS
        events = await cls.get_events(conversation_id)
        context = RequirementResolutionContext(policy=policy, events=events)

        snapshot = RequirementProjectionEngine.project(context)
        snapshot.projection_id = str(uuid.uuid4())
        snapshot.projection_timestamp = datetime.now(timezone.utc)

        # Persist
        await cls._save_snapshot(conversation_id, snapshot)
        return snapshot

    @classmethod
    async def _save_snapshot(cls, conversation_id: str, snapshot: RequirementSnapshot) -> None:
        from core.database import get_supabase
        now = datetime.now(timezone.utc).isoformat()
        try:
            get_supabase().table(cls.TABLE).upsert({
                "conversation_id": conversation_id,
                "latest_snapshot": snapshot.model_dump(mode="json"),
                "updated_at": now,
            }, on_conflict="conversation_id").execute()
        except Exception as exc:
            logger.error("[event_store] _save_snapshot failed: %s", exc, exc_info=True)


# ---------------------------------------------------------------------------
# Objective 2 — RequirementProjectionEngine + SnapshotProjection
# ---------------------------------------------------------------------------

class RequirementProjectionEngine:
    """Deterministic projection: events → snapshot (Objective 2).

    This is a PURE function (wrapped in a class for namespacing).
    Given a ``RequirementResolutionContext``, it produces a
    ``RequirementSnapshot``.

    Responsibilities (NO planner logic):
      - replay events in order
      - apply resolution policy
      - compute active components
      - compute assumptions
      - compute unknowns
      - compute conflicts
      - produce snapshot hash
    """
    @classmethod
    def project(cls, context: RequirementResolutionContext) -> RequirementSnapshot:
        """Deterministic projection.  Same context → same snapshot."""
        import time
        start_ms = int(time.time() * 1000)

        events = sorted(context.events, key=lambda e: e.timestamp)
        if not events:
            snap = RequirementSnapshot()
            snap.projection_version = 1
            return snap

        # ── Apply policy ─────────────────────────────────────────────────
        active_events = cls._apply_policy(events, context.policy)

        # ── Build snapshot fields ────────────────────────────────────────
        newest = active_events[-1] if active_events else events[-1]
        context.intent = newest.intent
        context.resolved_text = newest.payload.get("requirement_text", "")

        # Merge components (newest wins per component_type under NEWEST_WINS)
        comp_map: dict[str, DynamicComponent] = {}
        for ev in active_events:
            for c_dict in (ev.payload.get("components") or []):
                ct = c_dict.get("component_type", "UNKNOWN")
                comp = DynamicComponent(
                    id=f"{ct}-{len(comp_map) + 1}",
                    component_type=ct,
                    framework=c_dict.get("framework", "UNKNOWN"),
                    language=c_dict.get("language", "UNKNOWN"),
                    notes=c_dict.get("notes", ""),
                )
                comp_map[ct] = comp

        context.active_components = list(comp_map.values())

        # ── Compute unknowns + assumptions ─────────────────────────────
        context.unknowns = cls._compute_unknowns(context.active_components)
        context.assumptions = cls._compute_assumptions(context)

        # ── Detect conflicts ────────────────────────────────────────────
        context.conflicts = cls._detect_conflicts(active_events)

        # ── Assemble snapshot ───────────────────────────────────────────
        snap = RequirementSnapshot(
            snapshot_id=str(uuid.uuid4()),
            source_events=[e.event_id for e in events],
            requirement_text=context.resolved_text,
            intent=context.intent,
            components=context.active_components,
            assumptions=context.assumptions,
            conflicts=context.conflicts,
            event_count=len(events),
            revision_count=len(events),
        )
        snap.hash = cls._snapshot_hash(snap)
        snap.integrity_status = "valid"
        snap.projection_version = 1
        snap.projection_timestamp = datetime.now(timezone.utc)

        end_ms = int(time.time() * 1000)
        context.replay_duration_ms = end_ms - start_ms
        snap.replay_duration = context.replay_duration_ms

        return snap

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Policy application
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @classmethod
    def _apply_policy(
        cls,
        events: list[RequirementEvent],
        policy: ResolutionPolicy,
    ) -> list[RequirementEvent]:
        """Return the list of active (non-superseded) events after policy."""
        # Step 1: remove superseded events (all policies)
        superseded: set[str] = set()
        for ev in events:
            superseded.update(ev.supersedes)
        active = [ev for ev in events if ev.event_id not in superseded]

        if policy == ResolutionPolicy.NEWEST_WINS:
            # Already correct: all active events are kept; newest wins per field
            return active

        if policy == ResolutionPolicy.MERGE:
            # Keep all active events; conflicts are preserved (not resolved)
            return active

        if policy == ResolutionPolicy.REJECT:
            # If ANY conflict exists, reject ALL events after the first
            frameworks: dict[str, set[str]] = {}
            for ev in events:
                for c in (ev.payload.get("components") or []):
                    ct = c.get("component_type", "UNKNOWN")
                    fw = c.get("framework", "UNKNOWN")
                    frameworks.setdefault(ct, set()).add(fw)
            has_conflict = any(len(v) > 1 for v in frameworks.values())
            if has_conflict:
                # Keep only the first event
                return events[:1]
            return active

        # MANUAL + PRIORITY_WINS: keep all; conflicts recorded but not resolved
        return active

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Helpers
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @classmethod
    def _compute_unknowns(cls, components: list[DynamicComponent]) -> dict[str, UnknownType]:
        result: dict[str, UnknownType] = {}
        for c in components:
            if c.framework == "UNKNOWN":
                utype = UnknownType.REQUIRED if c.component_type in ("backend", "database") else UnknownType.OPTIONAL
                result[c.id] = utype
        return result

    @classmethod
    def _compute_assumptions(cls, context: RequirementResolutionContext) -> list[Assumption]:
        assumptions: list[Assumption] = []
        for c in context.active_components:
            if c.framework == "UNKNOWN":
                assumptions.append(Assumption(
                    field=f"{c.component_type}.framework",
                    value="UNKNOWN",
                    reason=f"User did not specify {c.component_type} framework.",
                    confidence=0.0,
                    priority=AssumptionPriority.CRITICAL,
                    can_be_confirmed=True,
                    approval_required=True,
                ))
        return assumptions

    @classmethod
    def _detect_conflicts(cls, events: list[RequirementEvent]) -> list[RequirementConflict]:
        conflicts: list[RequirementConflict] = []
        framework_map: dict[str, list[tuple[str, str]]] = {}
        for ev in events:
            for c in ((ev.payload or {}).get("components") or []):
                ct = c.get("component_type", "UNKNOWN")
                fw = c.get("framework", "UNKNOWN")
                framework_map.setdefault(ct, []).append((ev.event_id, fw))
        for ct, entries in framework_map.items():
            unique = {fw for _, fw in entries if fw != "UNKNOWN"}
            if len(unique) > 1:
                conflicts.append(RequirementConflict(
                    conflict_type="framework",
                    description=f"Multiple frameworks for '{ct}': {', '.join(unique)}",
                    conflicting_events=[eid for eid, _ in entries],
                    conflicting_values=list(unique),
                ))
        return conflicts

    @staticmethod
    def _snapshot_hash(snapshot: RequirementSnapshot) -> str:
        canonical = json.dumps(
            snapshot.model_dump(mode="json", exclude={"hash", "integrity_status"}),
            sort_keys=True,
            separators=(",", ":"),
            default=str,
        )
        return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# SnapshotProjection — metadata wrapper (Objective 2, 7)
# ---------------------------------------------------------------------------

class SnapshotProjection(BaseModel):
    """Metadata about a projection run (Objective 7 — provenance).

    Every ``RequirementSnapshot`` carries this as ``.projection``.
    """
    projection_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    projection_timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    source_event_count: int = 0
    replay_duration_ms: int = 0
    projection_version: int = 1
    projection_hash: str = ""        # hash of the snapshot at projection time
    policy: ResolutionPolicy = ResolutionPolicy.NEWEST_WINS


# ── Patch RequirementSnapshot to carry SnapshotProjection ───────────────────
#  (This is applied via a separate patch below to avoid circular edit conflicts)
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Objective 3 / 4 — Internal Domain Events + DomainEventPublisher
# ---------------------------------------------------------------------------

class InternalDomainEvent(str, Enum):
    """Internal domain events emitted by the Requirement layer (Objective 3).

    These are NOT external webhooks.  They are consumed internally by
    subscribers registered with ``DomainEventPublisher``.

    Future subscribers (Sprint 3+):
      - Approval System    — consumes ``CONFLICT_DETECTED``
      - Planner            — consumes ``SNAPSHOT_REBUILT``
      - Template Intelligence — consumes ``REQUIREMENT_UPDATED``
      - Audit UI          — consumes ALL events
    """
    REQUIREMENT_CREATED    = "requirement_created"
    REQUIREMENT_UPDATED    = "requirement_updated"
    REQUIREMENT_REMOVED    = "requirement_removed"
    REQUIREMENT_RESOLVED   = "requirement_resolved"
    REQUIREMENT_FROZEN     = "requirement_frozen"
    REQUIREMENT_ARCHIVED   = "requirement_archived"
    CONFLICT_DETECTED      = "conflict_detected"
    SNAPSHOT_REBUILT       = "snapshot_rebuilt"
    SPECIFICATION_GENERATED = "specification_generated"


class DomainEventPublisher:
    """Publish/subscribe for internal domain events (Objective 4).

    This is an in-memory pub/sub.  No Event Bus.  No external dispatch.

    The DEFAULT implementation is **NoOp** (nothing subscribed).
    Future systems subscribe by calling ``subscribe()``.

    Usage (Sprint 3+):
    ```python
    async def on_conflict(event_type, payload):
        # show conflict to user via Approval System
        ...

    DomainEventPublisher.subscribe(
        InternalDomainEvent.CONFLICT_DETECTED, on_conflict
    )
    ```
    """
    _subscribers: dict[InternalDomainEvent, list[Callable[..., Any]]] = {}
    _noop: bool = True        # no subscribers yet → skip publish overhead

    @classmethod
    def subscribe(cls, event_type: InternalDomainEvent, handler: Callable[..., Any]) -> None:
        cls._subscribers.setdefault(event_type, []).append(handler)
        cls._noop = False

    @classmethod
    def unregister(cls, event_type: InternalDomainEvent, handler: Callable[..., Any]) -> None:
        if event_type in cls._subscribers:
            try:
                cls._subscribers[event_type].remove(handler)
            except ValueError:
                pass
            if not cls._subscribers[event_type]:
                del cls._subscribers[event_type]
        cls._noop = len(cls._subscribers) == 0

    @classmethod
    async def publish(cls, event_type: InternalDomainEvent, payload: dict[str, Any]) -> None:
        """Publish an internal domain event to all subscribers."""
        if cls._noop:
            return
        handlers = cls._subscribers.get(event_type, [])
        for h in handlers:
            try:
                result = h(event_type, payload)
                if asyncio.iscoroutine(result):
                    await result
            except Exception as exc:
                logger.warning("[domain_events] handler %s failed: %s", h.__name__, exc)

    @classmethod
    def clear_all(cls) -> None:
        """Remove all subscribers (useful in tests)."""
        cls._subscribers.clear()
        cls._noop = True


# ---------------------------------------------------------------------------
# Objective 8 — ProjectionVerifier
# ---------------------------------------------------------------------------

class ProjectionVerifier:
    """Verify projection correctness (Objective 8).

    Responsibilities:
      - replay correctness  (same events + policy → same snapshot)
      - event ordering      (timestamp ordering is preserved)
      - hash consistency    (stored hash matches computed hash)
      - projection integrity (no events lost in projection)
      - conflict consistency (conflicts in snapshot match events)
      - assumption consistency (assumptions match unknowns)
    """
    @classmethod
    def verify(cls, events: list[RequirementEvent], snapshot: RequirementSnapshot) -> tuple[bool, list[str]]:
        issues: list[str] = []

        # 1. Event count consistency
        if snapshot.event_count != len(events):
            issues.append(
                f"event_count mismatch: snapshot says {snapshot.event_count}, "
                f"store has {len(events)}"
            )

        # 2. Source events completeness
        stored_ids = {e.event_id for e in events}
        snapshot_ids = set(snapshot.source_events or [])
        missing = stored_ids - snapshot_ids
        extra   = snapshot_ids - stored_ids
        if missing:
            issues.append(f"{len(missing)} events in store but not in snapshot source_events")
        if extra:
            issues.append(f"{len(extra)} events in snapshot source_events but not in store")

        # 3. Hash consistency
        computed = cls._hash(snapshot)
        if snapshot.hash and computed != snapshot.hash:
            issues.append(f"hash mismatch: stored={snapshot.hash[:8]} computed={computed[:8]}")

        # 4. Conflict consistency
        # (conflicts in snapshot should match what _detect_conflicts would return)
        # This is a simplified check: just ensure conflict event_ids are in source_events
        for c in (snapshot.conflicts or []):
            for eid in (c.conflicting_events or []):
                if eid not in snapshot_ids:
                    issues.append(f"conflict {c.conflict_id} references unknown event {eid}")

        return (len(issues) == 0, issues)

    @staticmethod
    def _hash(snapshot: RequirementSnapshot) -> str:
        canonical = json.dumps(
            snapshot.model_dump(mode="json", exclude={"hash", "integrity_status"}),
            sort_keys=True,
            separators=(",", ":"),
            default=str,
        )
        return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Objective 9 — Explicit domain service contracts (interfaces)
# ---------------------------------------------------------------------------
# These dataclasses/protocols define the contract each service must fulfil.
# The actual implementation lives in ``services/requirement_discovery.py``
# and the new ``services/projection.py`` (Sprint 2F).
# ---------------------------------------------------------------------------

class EventStoreProtocol(Protocol):
    """Contract for ``RequirementEventStore`` (Objective 9)."""
    async def append(self, conversation_id: str, event: RequirementEvent) -> None: ...
    async def get_events(self, conversation_id: str) -> list[RequirementEvent]: ...
    async def rebuild_snapshot(
        self, conversation_id: str, policy: ResolutionPolicy | None = None,
    ) -> RequirementSnapshot: ...


class ProjectionEngineProtocol(Protocol):
    """Contract for ``RequirementProjectionEngine`` (Objective 9)."""
    def project(self, context: RequirementResolutionContext) -> RequirementSnapshot: ...


class ProjectionVerifierProtocol(Protocol):
    """Contract for ``ProjectionVerifier`` (Objective 9)."""
    def verify(
        self, events: list[RequirementEvent], snapshot: RequirementSnapshot,
    ) -> tuple[bool, list[str]]: ...


class ResolutionPolicyProtocol(Protocol):
    """Contract for resolution policy (Objective 9)."""
    async def resolve(
        self, events: list[RequirementEvent], context: RequirementResolutionContext,
    ) -> RequirementSnapshot: ...


class DomainEventPublisherProtocol(Protocol):
    """Contract for ``DomainEventPublisher`` (Objective 9)."""
    async def publish(self, event_type: InternalDomainEvent, payload: dict[str, Any]) -> None: ...
    def subscribe(self, event_type: InternalDomainEvent, handler: Callable[..., Any]) -> None: ...
    def unregister(self, event_type: InternalDomainEvent, handler: Callable[..., Any]) -> None: ...


# ---------------------------------------------------------------------------
# Objective 10 — Architectural isolation enforcement (decorator)
# ---------------------------------------------------------------------------
# The following functions are provided as a development-time guard.
# They inspect the current stack to ensure the Requirement domain
# never calls into planner/executor/deployment/templates/approval.
# ---------------------------------------------------------------------------

def _assert_no_leakage() -> None:
    """Raise ``RuntimeError`` if caller leaks into forbidden modules.

    Forbidden:
      - services.planner
      - services.executor
      - services.deployment
      - services.templates
      - services.approval
      - services.workers
    """
    import traceback
    stack = traceback.extract_stack()
    for frame in stack:
        mod = frame.filename or ""
        if any(
            forbidden in mod
            for forbidden in (
                "services/planner",
                "services/executor",
                "services/deployment",
                "services/templates",
                "services/approval",
                "services/workers",
            )
        ):
            raise RuntimeError(
                f"Architectural leakage detected: "
                f"Requirement domain called into {mod}.  "
                f"See Objective 10 (Sprint 2F)."
            )


# ---------------------------------------------------------------------------
# Update RequirementSnapshot to carry SnapshotProjection (Objective 7)
# ---------------------------------------------------------------------------
# This is a PATCH applied below (separate from the big model patch above
# to avoid edit conflicts).  Adds these fields to RequirementSnapshot:
#
#   projection_id: str
#   projection_timestamp: datetime
#   source_event_count: int
#   replay_duration: int
#   projection_version: int
#   projection_hash: str
# ---------------------------------------------------------------------------


# ── (End of Sprint 2F model additions) ────────────────────────────────────
#  NOTE: the actual ``RequirementSnapshot`` model fields are patched below.
#  The ``ProjectSpecification`` model also gets a ``projection`` field.
# ─────────────────────────────────────────────────────────────────────────────

# ---------------------------------------------------------------------------
# Objective 4 — IntentType (NEW)
# ---------------------------------------------------------------------------
class IntentType(str, Enum):
    """Intent categories (Objective 4 — separate from requirement).

    Intent lives in the REQUIREMENT layer (not in Specification).
    """
    CREATE   = "create"
    MODIFY   = "modify"
    DELETE   = "delete"
    REPLACE  = "replace"
    CLARIFY = "clarify"
    CONFIGURE = "configure"
    DEPLOY   = "deploy"
    OPTIMIZE = "optimize"
    DEBUG    = "debug"
    EXTEND   = "extend"


# ---------------------------------------------------------------------------
# Objective 1 — RequirementEvent (NEW, immutable)
# ---------------------------------------------------------------------------
class RequirementEvent(BaseModel):
    """One immutable event representing a user (or system) instruction.

    Events are the SOURCE OF TRUTH.  Revisions and snapshots are
    DERIVED from events.  Events are NEVER edited.
    """
    event_id: str = Field(default_factory=lambda: _new_uuid())
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    source: str = "user"                 # "user" | "agent_inferred" | "system"
    event_type: str = "instruction"       # "instruction" | "amendment" | "removal" | "override"
    intent: IntentType = IntentType.CREATE
    event_schema_version: EventSchemaVersion = EventSchemaVersion.v1
    payload: dict[str, Any] = Field(default_factory=dict)
    # ── lineage ──────────────────────────────────────────────────────────
    supersedes: list[str] = Field(default_factory=list)   # event_ids this overrides
    affects: list[str] = Field(default_factory=list)     # component IDs affected
    # ── metadata ────────────────────────────────────────────────────────
    confidence: float = 1.0
    metadata: dict[str, Any] = Field(default_factory=dict)

    def supersedes_events(self) -> list[str]:
        return self.supersedes

    def is_override(self) -> bool:
        return len(self.supersedes) > 0


# ---------------------------------------------------------------------------
# Objective 3 — RequirementConflict (NEW)
# ---------------------------------------------------------------------------
class RequirementConflict(BaseModel):
    """An explicit conflict between two or more requirement events."""
    conflict_id: str = Field(default_factory=lambda: _new_uuid())
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    conflict_type: str = "framework"   # "framework" | "database" | "runtime" | "deployment" | "language" | "architecture"
    description: str = ""
    conflicting_events: list[str] = Field(default_factory=list)   # event_ids
    conflicting_values: list[str] = Field(default_factory=list)
    resolution: str = "unresolved"   # "unresolved" | "kept_newest" | "kept_oldest" | "manual"


# ---------------------------------------------------------------------------
# Objective 1 — RequirementSnapshot (derived from events)
# ---------------------------------------------------------------------------
class RequirementSnapshot(BaseModel):
    """Deterministic, immutable snapshot derived from ALL events.

    Built by ``RequirementResolutionEngine``.  This is the CANONICAL
    statement of what the user wants at a point in time.
    """
    snapshot_id: str = Field(default_factory=lambda: _new_uuid())
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    source_events: list[str] = Field(default_factory=list)   # event_ids
    requirement_text: str = ""            # resolved plain-text summary
    intent: IntentType = IntentType.CREATE
    # ── resolved architecture (from events) ────────────────────────────
    components: list[DynamicComponent] = Field(default_factory=list)
    assumptions: list[Assumption] = Field(default_factory=list)
    conflicts: list[RequirementConflict] = Field(default_factory=list)
    # ── integrity ───────────────────────────────────────────────────────
    hash: str = ""
    parent_hash: str = ""
    integrity_status: str = "pending"   # "pending" | "valid" | "tampered"
    event_count: int = 0
    revision_count: int = 0
    # ── Objective 7 — projection provenance ─────────────────────────────
    projection_id: str = ""
    projection_timestamp: datetime | None = None
    source_event_count: int = 0
    replay_duration: int = 0       # milliseconds
    projection_version: int = 1
    projection_hash: str = ""
    policy: ResolutionPolicy | None = None


# ---------------------------------------------------------------------------
# Objective 2 — RequirementResolutionEngine (NEW)
# ---------------------------------------------------------------------------
class RequirementResolutionEngine:
    """Deterministically build a ``RequirementSnapshot`` from events.

    Responsibilities:
      - detect overrides   (event A supersedes event B)
      - detect conflicts   (FastAPI vs Express in same snapshot)
      - detect duplicates  (identical events)
      - detect removals     (event says "remove cache")
      - detect amendments   (event changes one field)
      - resolve newest authoritative value

    The engine is a PURE function: same events → same snapshot.
    """
    @staticmethod
    def resolve(events: list[RequirementEvent]) -> RequirementSnapshot:
        if not events:
            return RequirementSnapshot()

        sorted_events = sorted(events, key=lambda e: e.timestamp)
        snapshot = RequirementSnapshot(
            source_events=[e.event_id for e in sorted_events],
            event_count=len(sorted_events),
        )

        # ── Pass 1: apply overrides (supersedes) ─────────────────────
        active_events: list[RequirementEvent] = []
        superseded = set()
        for ev in sorted_events:
            superseded.update(ev.supersedes)
        active_events = [ev for ev in sorted_events if ev.event_id not in superseded]

        # ── Pass 2: build resolved text + components ───────────────────
        newest = active_events[-1]
        snapshot.intent = newest.intent
        snapshot.requirement_text = newest.payload.get("requirement_text", "")

        # Merge components from all active events (newest wins per component_type)
        comp_map: dict[str, DynamicComponent] = {}
        for ev in active_events:
            for c in (ev.payload.get("components") or []):
                ct = c.get("component_type", "UNKNOWN")
                comp_map[ct] = DynamicComponent(**c)
        snapshot.components = list(comp_map.values())

        # ── Pass 3: detect conflicts ───────────────────────────────────
        frameworks: dict[str, list[str]] = {}   # component_type → [values]
        for ev in active_events:
            for c in (ev.payload.get("components") or []):
                ct = c.get("component_type", "UNKNOWN")
                fw = c.get("framework", "UNKNOWN")
                frameworks.setdefault(ct, []).append(fw)

        conflicts: list[RequirementConflict] = []
        for ct, fws in frameworks.items():
            unique = set(f for f in fws if f != "UNKNOWN")
            if len(unique) > 1:
                conflicts.append(RequirementConflict(
                    conflict_type="framework",
                    description=f"Multiple frameworks for {ct}: {', '.join(unique)}",
                    conflicting_values=list(unique),
                ))
        snapshot.conflicts = conflicts

        # ── Pass 4: compute integrity hash ────────────────────────────
        snapshot.event_count = len(sorted_events)
        snapshot.revision_count = len(sorted_events)   # 1 revision ≈ 1 event for now
        snapshot.hash = _snapshot_hash(snapshot)
        snapshot.integrity_status = "valid"
        return snapshot


# ---------------------------------------------------------------------------
# Objective 5 — RelationshipGraph (NEW)
# ---------------------------------------------------------------------------
class RelationshipGraph(BaseModel):
    """Relationship graph for architecture components.

    Each component declares what it ``provides``, ``consumes``,
    ``depends_on``, ``required_by``, ``interfaces``, ``runtime``, ``lifecycle``.

    The Planner consumes this graph in Sprint 3 to order execution steps.
    """
    components: list[DynamicComponent] = Field(default_factory=list)

    def build_from(self, components: list[DynamicComponent]) -> "RelationshipGraph":
        self.components = components
        # Auto-populate depends_on / required_by from component.dependencies
        id_map = {c.id: c for c in self.components}
        for c in self.components:
            c.dependencies = c.dependencies or []
            # If dependencies is empty but component_type implies defaults, fill them
            if not c.dependencies:
                if c.component_type == "queue" and id_map.get("backend-api"):
                    c.dependencies.append("backend-api")
        return self

    def get_execution_order(self) -> list[str]:
        """Topological sort (planner will use this in Sprint 3)."""
        # Simplified: just return component IDs in dependency order
        ordered: list[str] = []
        visited: set[str] = set()

        def _dfs(cid: str):
            if cid in visited:
                return
            visited.add(cid)
            c = next((x for x in self.components if x.id == cid), None)
            if c:
                for dep in (c.dependencies or []):
                    _dfs(dep)
            ordered.append(cid)

        for c in self.components:
            _dfs(c.id)
        return ordered

    def to_dict(self) -> dict[str, Any]:
        return {
            "components": [c.component_type for c in self.components],
            "dependencies": {c.id: c.dependencies for c in self.components},
            "execution_order": self.get_execution_order(),
        }


# ---------------------------------------------------------------------------
# Objective 6 — RequirementState (state machine)
# ---------------------------------------------------------------------------
class RequirementState(str, Enum):
    """Lifecycle state machine for a requirement snapshot."""
    DRAFT      = "draft"       # being constructed
    INCOMPLETE = "incomplete"  # missing critical fields
    READY      = "ready"       # complete, can plan
    FROZEN     = "frozen"      # frozen, hash computed
    ARCHIVED   = "archived"    # superseded by newer snapshot


# Legal transitions:
#   DRAFT      → INCOMPLETE | READY
#   INCOMPLETE → READY
#   READY      → FROZEN
#   FROZEN     → ARCHIVED (only when newer snapshot frozen)
#   ARCHIVED   → (terminal)
_ALLOWED_TRANSITIONS: dict[RequirementState, set[RequirementState]] = {
    RequirementState.DRAFT:      {RequirementState.INCOMPLETE, RequirementState.READY},
    RequirementState.INCOMPLETE: {RequirementState.READY},
    RequirementState.READY:      {RequirementState.FROZEN},
    RequirementState.FROZEN:     {RequirementState.ARCHIVED},
    RequirementState.ARCHIVED:   set(),   # terminal
}


def _validate_transition(current: RequirementState, target: RequirementState) -> bool:
    return target in _ALLOWED_TRANSITIONS.get(current, set())


# ---------------------------------------------------------------------------
# Objective 7 — SpecificationLineage (NEW)
# ---------------------------------------------------------------------------
class SpecificationLineage(BaseModel):
    """Full traceability: Specification ← RequirementSnapshot ← Events."""
    lineage_id: str = Field(default_factory=lambda: _new_uuid())
    source_snapshot_id: str = ""       # RequirementSnapshot.snapshot_id
    source_snapshot_hash: str = ""    # RequirementSnapshot.hash
    parent_lineage_id: str | None = None
    created_from_version: int | None = None
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    event_count: int = 0
    revision_count: int = 0
    integrity_status: str = "valid"     # "valid" | "broken"


# ---------------------------------------------------------------------------
# Objective 8 — RequirementIntegrity (NEW)
# ---------------------------------------------------------------------------
class RequirementIntegrity:
    """Verify integrity of a ``RequirementSnapshot`` independently."""
    @staticmethod
    def verify(snapshot: RequirementSnapshot) -> tuple[bool, list[str]]:
        issues: list[str] = []
        # 1. Hash consistency
        computed = _snapshot_hash(snapshot)
        if snapshot.hash and computed != snapshot.hash:
            issues.append(f"Snapshot hash mismatch: stored={snapshot.hash[:8]} computed={computed[:8]}")
            snapshot.integrity_status = "tampered"
        else:
            snapshot.integrity_status = "valid"

        # 2. Event count consistency
        if snapshot.event_count < 0:
            issues.append("event_count is negative")

        # 3. Conflicts unresolved
        unresolved = [c for c in snapshot.conflicts if c.resolution == "unresolved"]
        if unresolved:
            issues.append(f"{len(unresolved)} unresolved conflict(s)")

        return (len(issues) == 0, issues)

    @staticmethod
    def compute_hash(snapshot: RequirementSnapshot) -> str:
        return _snapshot_hash(snapshot)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _new_uuid() -> str:
    import uuid
    return str(uuid.uuid4())


def _snapshot_hash(snapshot: RequirementSnapshot) -> str:
    import hashlib
    canonical = json.dumps(
        snapshot.model_dump(mode="json", exclude={"hash", "integrity_status"}),
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Objective 9 — Domain service interfaces (cleanup)
# ---------------------------------------------------------------------------
# These are MARKER classes / protocols.  The actual logic lives in
# ``services/requirement_discovery.py``.  These definitions exist in
# ``models/agent.py`` so that every layer shares the same interface contract.
# ---------------------------------------------------------------------------

class RequirementRepository:
    """Persistence contract (Objective 9).

    Responsibilities:
      - Load/save ``RequirementDocument`` (events + snapshots)
      - NEVER touches Planner, Execution, Deployment, Templates, or Approval.
    """
    async def get_events(self, conversation_id: str) -> list[RequirementEvent]: ...
    async def append_event(self, conversation_id: str, event: RequirementEvent) -> None: ...
    async def get_latest_snapshot(self, conversation_id: str) -> RequirementSnapshot | None: ...
    async def save_snapshot(self, conversation_id: str, snapshot: RequirementSnapshot) -> None: ...


class RequirementResolver:
    """Resolution contract (Objective 9).

    Responsibilities:
      - Build ``RequirementSnapshot`` from events
      - Detect and record conflicts
      - Produce deterministic, reproducible snapshot
    """
    async def resolve(self, events: list[RequirementEvent]) -> RequirementSnapshot: ...


class RequirementMapper:
    """Mapping contract (Objective 9 — updated from Sprint 2D).

    Responsibilities:
      - Translate ``RequirementSnapshot`` → ``DynamicArchitecture`` + ``list[Assumption]``
      - PURE function: no side effects, no LLM, no validation
    """
    async def map(self, snapshot: RequirementSnapshot) -> tuple[DynamicArchitecture, list[Assumption]]: ...


class RequirementValidator:
    """Validation contract (Objective 9).

    Responsibilities:
      - Validate resolved snapshot for consistency
      - Detect impossible combinations
      - Produce validation errors/warnings
    """
    async def validate(self, snapshot: RequirementSnapshot) -> tuple[bool, list[str], list[str]]: ...


class RequirementReview:
    """Review contract (Objective 9).

    Responsibilities:
      - Review the snapshot + mapped architecture
      - Produce review verdict (pass/pass_with_warnings/fail)
      - Does NOT modify the snapshot
    """
    async def review(self, snapshot: RequirementSnapshot) -> dict[str, Any]: ...


class RequirementSnapshotBuilder:
    """Snapshot building contract (Objective 9).

    Responsibilities:
      - Assemble ``RequirementSnapshot`` from events
      - Apply state machine transitions
      - Compute integrity hash
    """
    async def build(self, events: list[RequirementEvent]) -> RequirementSnapshot: ...


class RequirementIntegrityService:
    """Integrity contract (Objective 9).

    Responsibilities:
      - Verify snapshot integrity independently
      - Detect tampering
      - Produce integrity report
    """
    async def verify(self, snapshot: RequirementSnapshot) -> tuple[bool, list[str]]: ...


# ---------------------------------------------------------------------------
# Objective 5 helper — build graph from DynamicArchitecture
# ---------------------------------------------------------------------------
def build_relationship_graph(arch: DynamicArchitecture) -> RelationshipGraph:
    """Build a ``RelationshipGraph`` from a ``DynamicArchitecture``."""
    graph = RelationshipGraph()
    graph.build_from(arch.components)
    return graph


# ---------------------------------------------------------------------------
# Updated ProjectSpecification (Objective 7 — lineage)
# ---------------------------------------------------------------------------
# (The model definition below is APPENDED — it does NOT replace the Sprint 2D model.
#  Sprint 2E adds ``lineage`` field to ``ProjectSpecification``.)

# See the PATCH below for the actual field addition.
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Cleanup: remove architectural leakage (Objective 10)
# ---------------------------------------------------------------------------
# The following imports are NOT allowed in this domain model file:
#
#   ❌  from services.planner import ...
#   ❌  from services.executor import ...
#   ❌  from services.approval import ...
#   ❌  from services.templates import ...
#
# The Requirement domain MUST ONLY import:
#   ✅  pydantic
#   ✅  standard library (json, hashlib, uuid, enum, datetime)
#   ✅  its own models (Assumption, DynamicComponent, ...)
#
# This is enforced by code review (Sprint 2E does NOT add those imports).
# ---------------------------------------------------------------------------


# ── (The rest of models/agent.py continues below) ─────────────────────────
#  NOTE: the actual ``ProjectSpecification`` model from Sprint 2D is
#  PRESERVED.  Sprint 2E only ADDS the ``lineage`` field via a
#  separate patch (see below).

    """Priority tiers for assumptions (Objective 4 — Sprint 2D)."""
    CRITICAL = "critical"
    HIGH     = "high"
    MEDIUM   = "medium"
    LOW      = "low"


class UnknownType(str, Enum):
    """Classify UNKNOWN values so the planner can decide how to proceed."""
    REQUIRED   = "unknown_required"
    OPTIONAL   = "unknown_optional"
    EXTERNAL  = "unknown_external"
    DEFERRED  = "unknown_deferred"


# ---------------------------------------------------------------------------
# Objective 3 (updated) — Assumption
# ---------------------------------------------------------------------------
class Assumption(BaseModel):
    """Explicit assumption the agent makes when it cannot determine a fact.

    Assumptions are NOT part of the requirement or the specification.
    They are separate metadata that the future Approval System will consume.

    Sprint 2D update: added ``priority`` field (Objective 4).
    """
    field: str
    value: str
    reason: str
    confidence: float = 0.5
    priority: AssumptionPriority = AssumptionPriority.MEDIUM
    can_be_confirmed: bool = True
    approval_required: bool = False
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ---------------------------------------------------------------------------
# Objective 1 — RequirementDocument (completely NEW)
# ---------------------------------------------------------------------------
class RequirementChange(BaseModel):
    """One change entry in a requirement revision."""
    field: str
    old_value: str | None = None
    new_value: str | None = None


class RequirementRevision(BaseModel):
    """One immutable version of a ``RequirementDocument``.

    Requirement revisions are VERSIONED and IMPORTABLE.
    They survive specification rebuilds.
    """
    version: int = 1
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    source: str = "user"            # "user" | "agent_inferred" | "system"
    change_reason: str = ""
    changed_fields: list[str] = Field(default_factory=list)
    # Free-text requirement as the user expressed it (or as refined)
    requirement_text: str = ""
    # Structured extraction result (intermediate, NOT the spec)
    extracted_components: list[dict[str, Any]] = Field(default_factory=list)
    assumptions: list[Assumption] = Field(default_factory=list)


class RequirementDocument(BaseModel):
    """Immutable record of WHAT the user wants.

    This is completely SEPARATE from ``ProjectSpecification``.

    - ``revisions`` — append-only version history (never overwritten)
    - ``latest_revision`` — pointer to the latest revision
    - ``timeline`` — summarises how requirements evolved (Objective 2)

    The Planner MUST NEVER read ``RequirementDocument`` directly.
    It MUST always consume ``FrozenSpecification``.
    """
    conversation_id: str = ""
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    revisions: list[RequirementRevision] = Field(default_factory=list)
    latest_revision: int = 0

    def add_revision(
        self,
        requirement_text: str,
        source: str = "user",
        change_reason: str = "",
        changed_fields: list[str] | None = None,
        extracted_components: list[dict[str, Any]] | None = None,
        assumptions: list[Assumption] | None = None,
    ) -> RequirementRevision:
        """Append a new immutable revision.  Returns the new revision."""
        new_version = self.latest_revision + 1
        rev = RequirementRevision(
            version=new_version,
            timestamp=datetime.now(timezone.utc),
            source=source,
            change_reason=change_reason,
            changed_fields=changed_fields or [],
            requirement_text=requirement_text,
            extracted_components=extracted_components or [],
            assumptions=assumptions or [],
        )
        self.revisions.append(rev)
        self.latest_revision = new_version
        self.updated_at = rev.timestamp
        return rev

    def get_latest(self) -> RequirementRevision | None:
        if not self.revisions:
            return None
        return self.revisions[-1]

    def get_revision(self, version: int) -> RequirementRevision | None:
        for r in self.revisions:
            if r.version == version:
                return r
        return None

    def diff(self, v1: int, v2: int) -> dict[str, Any]:
        """Produce a diff between two requirement versions (Objective 7)."""
        r1 = self.get_revision(v1)
        r2 = self.get_revision(v2)
        if not r1 or not r2:
            return {"error": "version not found"}
        added: list[str] = []
        removed: list[str] = []
        modified: list[dict[str, str]] = []
        unchanged: list[str] = []

        # Compare requirement_text naively (line-by-line)
        t1_lines = set(r1.requirement_text.splitlines())
        t2_lines = set(r2.requirement_text.splitlines())
        for line in t2_lines - t1_lines:
            added.append(line[:120])
        for line in t1_lines - t2_lines:
            removed.append(line[:120])
        for line in t1_lines & t2_lines:
            unchanged.append(line[:120])

        return {
            "added": added,
            "removed": removed,
            "modified": modified,
            "unchanged": unchanged,
        }


# ---------------------------------------------------------------------------
# Objective 5 — RequirementMapper (NEW)
# ---------------------------------------------------------------------------
class RequirementMapper:
    """Deterministic translation layer.

    RequirementDocument
        ↓
    RequirementMapper.translate()
        ↓
    Architecture + Assumptions

    This layer contains NO planner logic, NO execution logic,
    and NO validation logic.  It ONLY translates.
    """
    @staticmethod
    def translate(
        revision: RequirementRevision,
    ) -> tuple[Any, list[Assumption]]:
        """Translate a ``RequirementRevision`` into ``Architecture`` + ``Assumption`` list.

        This is a pure function — same input ALWAYS produces same output.
        """
        # If the revision already has extracted_components (from LLM), use them
        if revision.extracted_components:
            return _build_architecture_from_components(revision.extracted_components)

        # Otherwise, re-extract from requirement_text
        from services.requirement_discovery import (
            RequirementExtractor, _build_architecture, _build_assumptions,
        )
        arch, assumptions = RequirementExtractor._regex_fallback_architecture(
            revision.requirement_text
        )
        return arch, assumptions


# ---------------------------------------------------------------------------
# Objective 2 — ArchitectureComponent (DYNAMIC, Objective 3)
# ---------------------------------------------------------------------------
class DynamicComponent(BaseModel):
    """A single architecture component with dynamic/arbitrary types.

    Replaces the fixed ``ArchitectureComponent`` model.

    This model supports FUTURE component types (MCP, Agent Cluster, Event Bus, …)
    WITHOUT changing the model schema.
    """
    id: str = ""                    # e.g. "backend-api", "queue-worker"
    component_type: str = "UNKNOWN" # "frontend", "backend", "database", "cache",
                                      # "queue", "proxy", "monitoring", "auth",
                                      # "gateway", "plugin", "event_bus", "mcp",
                                      # "agent_cluster", …
    framework: str = "UNKNOWN"
    language: str = "UNKNOWN"
    version_constraint: str = "UNKNOWN"
    capabilities: list[str] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)   # component IDs this depends on
    configuration: dict[str, Any] = Field(default_factory=dict)
    unknown_type: UnknownType | None = None
    notes: str = ""


class DynamicArchitecture(BaseModel):
    """Dynamic architecture — supports arbitrary future component types.

    Replaces ``Architecture`` (fixed list of component names).

    To add a new component type (e.g. ``"mcp"``), just append a
    ``DynamicComponent(component_type="mcp", …)`` — NO schema change needed.
    """
    components: list[DynamicComponent] = Field(default_factory=list)
    raw_text: str = ""

    def get_component(self, component_id: str) -> DynamicComponent | None:
        for c in self.components:
            if c.id == component_id or c.component_type == component_id:
                return c
        return None

    def get_components_by_type(self, ctype: str) -> list[DynamicComponent]:
        return [c for c in self.components if c.component_type == ctype]


# ---------------------------------------------------------------------------
# SpecificationVersion (updated for Sprint 2D — links to requirement version)
# ---------------------------------------------------------------------------
class SpecificationVersion(BaseModel):
    """One version of a ``ProjectSpecification``.

    Sprint 2D: added ``requirement_version`` to link spec version
    to the exact requirement revision that produced it.
    """
    version: int = 1
    requirement_version: int | None = None   # which RequirementRevision produced this
    spec_json: dict[str, Any] = Field(default_factory=dict)
    frozen_at: datetime | None = None
    frozen_hash: str = ""
    parent_spec_version: int | None = None
    change_reason: str = ""
    changed_fields: list[str] = Field(default_factory=list)
    review_verdict: str = "pass"


# ---------------------------------------------------------------------------
# FrozenSpecification (unchanged from Sprint 2C)
# ---------------------------------------------------------------------------
class FrozenSpecification(BaseModel):
    """Immutable, tamper-aware wrapper around a frozen specification."""
    spec: dict[str, Any] = Field(default_factory=dict)
    frozen_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    frozen_hash: str = ""
    version: int = 1
    requirement_version: int | None = None
    is_tampered: bool = False

    def compute_hash(self) -> str:
        import hashlib
        canonical = json.dumps(
            self.spec,
            sort_keys=True,
            separators=(",", ":"),
            default=str,
        )
        return hashlib.sha256(canonical.encode("utf-8")).hexdigest()

    def validate_hash(self) -> bool:
        if not self.frozen_hash:
            return False
        return self.compute_hash() == self.frozen_hash

    def mark_tampered(self) -> None:
        self.is_tampered = True


# ---------------------------------------------------------------------------
# ProjectSpecification (updated for Sprint 2D)
# ---------------------------------------------------------------------------
class ProjectSpecification(BaseModel):
    """Structured project specification — technical interpretation of requirements.

    Sprint 2D changes:
    - ``architecture`` is now ``DynamicArchitecture`` (supports arbitrary types)
    - ``requirement_version`` links to the producing ``RequirementRevision``
    - ``assumptions`` now have ``priority`` field
    - ``frozen_spec.requirement_version`` tracks provenance
    """
    # --- Deprecated scalar fields (kept for backward compatibility) ---
    project_type: str = "UNKNOWN"
    framework: str = "UNKNOWN"
    language: str = "UNKNOWN"
    features: list[str] = Field(default_factory=list)
    auth_required: bool = False
    database_required: bool = False
    external_services: list[str] = Field(default_factory=list)
    secrets_required: list[str] = Field(default_factory=list)
    deployment_target: str = "UNKNOWN"
    production_ready: bool = False

    # --- Sprint 2D — new architecture model ---
    architecture: DynamicArchitecture = Field(default_factory=DynamicArchitecture)

    # --- Assumptions (with priority) ---
    assumptions: list[Assumption] = Field(default_factory=list)

    # --- UNKNOWN classification ---
    unknown_fields: dict[str, UnknownType] = Field(default_factory=dict)

    # --- Versioning ---
    versions: list[SpecificationVersion] = Field(default_factory=list)
    current_version: int = 1
    requirement_version: int | None = None   # which RequirementRevision produced this

    # --- Sprint 2E — lineage (Objective 7) ---
    lineage: SpecificationLineage | None = None
    # --- Sprint 2F — projection (Objective 7) ---
    projection: SnapshotProjection | None = None

    # --- Readiness & freeze ---
    readiness: str = "Blocked"
    frozen: bool = False
    frozen_spec: FrozenSpecification | None = None

    # --- Metadata ---
    missing_info: list[str] = Field(default_factory=list)
    needs_user_input: bool = False
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # --- Constructors ---
    @classmethod
    def from_dynamic_architecture(
        cls,
        arch: DynamicArchitecture,
        **kwargs: Any,
    ) -> "ProjectSpecification":
        """Build from ``DynamicArchitecture`` (replaces ``from_architecture``)."""
        backend = arch.get_component("backend")
        database = arch.get_component("database")
        return cls(
            architecture=arch,
            framework=backend.framework if backend else "UNKNOWN",
            language=backend.language if backend else "UNKNOWN",
            database_required=(
                database is not None and database.framework != "UNKNOWN"
            ),
            **kwargs,
        )

    # --- Helpers ---
    def is_critical_unknown(self) -> list[str]:
        blocked: list[str] = []
        for field_name, utype in self.unknown_fields.items():
            if utype == UnknownType.REQUIRED:
                blocked.append(field_name)
        return blocked

    def readiness_computed(self) -> str:
        if self.is_critical_unknown():
            return "Blocked"
        if any(
            c.unknown_type == UnknownType.REQUIRED
            for c in self.architecture.components
        ):
            return "Blocked"
        if not self.architecture.components:
            return "Partial"
        return "Ready"

    def to_canonical_json(self) -> str:
        return json.dumps(
            self.model_dump(mode="json"),
            sort_keys=True,
            separators=(",", ":"),
            default=str,
        )
    production_ready: bool = False
    missing_info: list[str] = Field(default_factory=list)
    # confidence is REMOVED (Sprint 2B).
    # Replaced by: readiness (Ready|Blocked|Partial) and frozen (bool).
    readiness: str = "Blocked"
    frozen: bool = False
    needs_user_input: bool = False
