from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class AgentTier(str, Enum):
    FORGE_V1 = "forge-v1"
    FORGE_V2 = "forge-v2"


class AgentJobStatus(str, Enum):
    QUEUED = "queued"
    RUNNING = "running"
    WAITING_FOR_LLM = "waiting_for_llm"
    COMPLETED = "completed"
    FAILED = "failed"


class ToolName(str, Enum):
    RUN_COMMAND = "run_command"
    CHECK_DISK = "check_disk"
    CHECK_MEMORY = "check_memory"
    RESTART_SERVICE = "restart_service"
    READ_LOGS = "read_logs"
    DEPLOY_APP = "deploy_app"
    DEPLOY_NEXTJS_APP = "deploy_nextjs_app"


class DecisionAction(str, Enum):
    CONTINUE = "continue"
    RETRY = "retry"
    MODIFY = "modify"
    ABORT = "abort"


class AgentPlanStep(BaseModel):
    step: int = Field(..., ge=1)
    command: str
    rationale: str
    approved: bool = True


class AgentRunRequest(BaseModel):
    server_id: str
    objective: str = Field(..., min_length=3, max_length=500)
    max_steps: int = Field(default=5, ge=1, le=10)
    allow_write: bool = False
    dry_run: bool = False
    step_timeout_seconds: int | None = Field(default=None, ge=5, le=300)
    max_concurrency: int | None = Field(default=None, ge=1, le=5)


class AgentExecutionResult(BaseModel):
    command: str
    output: str
    exit_code: int
    executed_at: datetime


class ArchitectureHistoryItem(BaseModel):
    id: str
    objective: str
    summary: str
    success: bool
    created_at: datetime


class AgentRunResponse(BaseModel):
    agent: AgentTier = AgentTier.FORGE_V1
    objective: str
    dry_run: bool
    policy: dict[str, str | int | bool]
    plan: list[AgentPlanStep]
    results: list[AgentExecutionResult]
    summary: str


class AgentOrchestrationRequest(BaseModel):
    workspace_id: str
    message: str = Field(..., min_length=3, max_length=20000)
    max_steps: int = Field(default=5, ge=1, le=10)
    allow_write: bool = False
    dry_run: bool = False
    step_timeout_seconds: int | None = Field(default=None, ge=5, le=300)
    max_concurrency: int | None = Field(default=None, ge=1, le=5)


class AgentOrchestrationResponse(BaseModel):
    agent: AgentTier = AgentTier.FORGE_V1
    chat_id: str
    user_message_id: str
    assistant_message_id: str
    run: AgentRunResponse
    architecture_history: list[ArchitectureHistoryItem]


class AgentPlanResponse(BaseModel):
    agent: AgentTier = AgentTier.FORGE_V1
    objective: str
    dry_run: bool = True
    policy: dict[str, str | int | bool]
    plan: list[AgentPlanStep]
    summary: str


class AgentAsyncRunAccepted(BaseModel):
    job_id: str
    status: AgentJobStatus = AgentJobStatus.QUEUED


class AgentJobResponse(BaseModel):
    job_id: str
    status: AgentJobStatus
    run: AgentRunResponse | None = None
    error: str | None = None


# ── Forge v2 models ────────────────────────────────────────────────────────────


class AgentStep(BaseModel):
    """A single step in an LLM-generated execution plan."""

    step: int = Field(..., ge=1)
    tool: ToolName
    args: dict[str, Any] = Field(default_factory=dict)
    rationale: str


class AgentPlan(BaseModel):
    """Full execution plan generated by the LLM."""

    objective: str
    steps: list[AgentStep]
    context_summary: str = ""


class StepResult(BaseModel):
    """Result from executing one agent step via a tool."""

    step: int
    tool: ToolName
    args: dict[str, Any]
    stdout: str = ""
    stderr: str = ""
    exit_code: int = 0
    duration_ms: int = 0
    executed_at: datetime
    success: bool


class AgentDecision(BaseModel):
    """LLM decision after evaluating a step result."""

    action: DecisionAction
    reason: str
    modified_step: AgentStep | None = None
    summary_so_far: str = ""


class ToolCallingLoopResult(BaseModel):
    """Result of the OpenAI tool-calling agent loop."""

    task_mode: str = "complex"
    plan: list[AgentStep] = []
    steps: list[StepResult] = []
    decisions: list[AgentDecision] = []
    summary: str = ""
    success: bool = True
    steps_taken: int = 0


class ForgeV2RunRequest(BaseModel):
    workspace_id: str | None = None
    server_id: str
    objective: str = Field(..., min_length=3, max_length=1000)
    max_steps: int = Field(default=8, ge=1, le=20)
    max_retries: int | None = Field(default=None, ge=0, le=5)
    allow_write: bool = False
    dry_run: bool = False
    step_timeout_seconds: int | None = Field(default=None, ge=5, le=600)


class ForgeV2StepAudit(BaseModel):
    """Row persisted to agent_runs for each step."""

    job_id: str
    step: int
    tool: str
    args: dict[str, Any]
    stdout: str
    stderr: str
    exit_code: int
    duration_ms: int
    decision: str
    decision_reason: str
    executed_at: datetime


class ForgeV2RunResponse(BaseModel):
    agent: AgentTier = AgentTier.FORGE_V2
    job_id: str
    objective: str
    dry_run: bool
    plan: list[AgentStep]
    results: list[StepResult]
    decisions: list[AgentDecision]
    summary: str
    success: bool


class ForgeV2JobResponse(BaseModel):
    job_id: str
    status: AgentJobStatus
    run: ForgeV2RunResponse | None = None
    error: str | None = None


class ForgeV2PlanResponse(BaseModel):
    agent: AgentTier = AgentTier.FORGE_V2
    job_id: str
    objective: str
    plan: list[AgentStep]
    context_summary: str
